# Generated by Django 4.1.7 on 2023-07-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal_age',
            field=models.IntegerField(max_length=100),
        ),
    ]
