# Generated by Django 4.1.7 on 2023-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_animal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal_age',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
