# Generated by Django 4.1.7 on 2023-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_animal_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='animal_age',
        ),
        migrations.AddField(
            model_name='patient',
            name='animal_age',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
